# --- Serving options --- #
title: Kimsa
description: K

# --- Outputting options --- #
# More information can be found on Jekyll's site
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

# --- Navigation bar options --- #
# Image to show in the navigation bar - image must be a square (width = height)
avatar: "/img/final5x5.png"

# List of links in the navigation bar
navbar-links:
#  Próximos eventos:
#    - Conferencia estadística: "conf_stat2018"
#    - Jornadas R: "jornadas_r2018"
  Blog R:
    - Temario: "publicaciones"
    - Etiquetas: "tags"
  Servicios:
    - Capacitación permanente: "cursos"
    - Consultoría: "consultoria"
  Nosotros:
    - ¿Quiénes somos?: "about"
    - Contacto: "contact"
  Únete:
    - como miembro: "join"
    - como miembro editor: "join_editor"
    - como Consultor: "consul"



# Exclude these files from production site
exclude:
  - CNAME
  - CNAME1
  - LICENSE
  - README.md 
